// AUTO-GENERATED iz stvarnih slika u /public/images/kits/.
// Transparentni WebP (GrabCut izrezivanje - prava alpha transparentnost).
// Irak i Iran nemaju slike i koriste SVG placeholder.
export const KIT_IMAGES = {
  "alzir": { home: "/images/kits/alzir-home.webp" },
  "argentina": { home: "/images/kits/argentina-home.webp", away: "/images/kits/argentina-away.webp" },
  "australija": { home: "/images/kits/australija-home.webp", away: "/images/kits/australija-away.webp" },
  "austrija": { home: "/images/kits/austrija-home.webp" },
  "belgija": { home: "/images/kits/belgija-home.webp", away: "/images/kits/belgija-away.webp" },
  "bosna": { home: "/images/kits/bosna-home.webp", away: "/images/kits/bosna-away.webp" },
  "brazil": { home: "/images/kits/brazil-home.webp", away: "/images/kits/brazil-away.webp" },
  "ceska": { home: "/images/kits/ceska-home.webp" },
  "curacao": { home: "/images/kits/curacao-home.webp", away: "/images/kits/curacao-away.webp" },
  "drkongo": { home: "/images/kits/drkongo-home.webp", away: "/images/kits/drkongo-away.webp" },
  "egipat": { home: "/images/kits/egipat-home.webp", away: "/images/kits/egipat-away.webp" },
  "ekvador": { home: "/images/kits/ekvador-home.webp", away: "/images/kits/ekvador-away.webp" },
  "engleska": { home: "/images/kits/engleska-home.webp", away: "/images/kits/engleska-away.webp" },
  "france": { home: "/images/kits/france-home.webp", away: "/images/kits/france-away.webp" },
  "gana": { home: "/images/kits/gana-home.webp" },
  "haiti": { home: "/images/kits/haiti-home.webp", away: "/images/kits/haiti-away.webp" },
  "holandija": { home: "/images/kits/holandija-home.webp", away: "/images/kits/holandija-away.webp" },
  "hrvatska": { home: "/images/kits/hrvatska-home.webp", away: "/images/kits/hrvatska-away.webp" },
  "japan": { home: "/images/kits/japan-home.webp", away: "/images/kits/japan-away.webp" },
  "jordan": { home: "/images/kits/jordan-home.webp", away: "/images/kits/jordan-away.webp" },
  "juznaafrika": { home: "/images/kits/juznaafrika-home.webp", away: "/images/kits/juznaafrika-away.webp" },
  "juznakoreja": { home: "/images/kits/juznakoreja-home.webp" },
  "kanada": { home: "/images/kits/kanada-home.webp", away: "/images/kits/kanada-away.webp" },
  "kapeverde": { home: "/images/kits/kapeverde-home.webp", away: "/images/kits/kapeverde-away.webp" },
  "katar": { home: "/images/kits/katar-home.webp", away: "/images/kits/katar-away.webp" },
  "kolumbija": { home: "/images/kits/kolumbija-home.webp", away: "/images/kits/kolumbija-away.webp" },
  "maroko": { home: "/images/kits/maroko-home.webp" },
  "meksiko": { home: "/images/kits/meksiko-home.webp", away: "/images/kits/meksiko-away.webp" },
  "nemacka": { home: "/images/kits/nemacka-home.webp", away: "/images/kits/nemacka-away.webp" },
  "norveska": { home: "/images/kits/norveska-home.webp", away: "/images/kits/norveska-away.webp" },
  "novizeland": { home: "/images/kits/novizeland-home.webp" },
  "obala": { home: "/images/kits/obala-home.webp" },
  "panama": { home: "/images/kits/panama-home.webp", away: "/images/kits/panama-away.webp" },
  "paragvaj": { home: "/images/kits/paragvaj-home.webp" },
  "portugal": { home: "/images/kits/portugal-home.webp", away: "/images/kits/portugal-away.webp" },
  "sad": { home: "/images/kits/sad-home.webp", away: "/images/kits/sad-away.webp" },
  "saudijska": { home: "/images/kits/saudijska-home.webp" },
  "senegal": { home: "/images/kits/senegal-home.webp" },
  "skotska": { home: "/images/kits/skotska-home.webp", away: "/images/kits/skotska-away.webp" },
  "spanija": { home: "/images/kits/spanija-home.webp", away: "/images/kits/spanija-away.webp" },
  "svajcarska": { home: "/images/kits/svajcarska-home.webp" },
  "svedska": { home: "/images/kits/svedska-home.webp", away: "/images/kits/svedska-away.webp" },
  "tunis": { home: "/images/kits/tunis-home.webp", away: "/images/kits/tunis-away.webp" },
  "turska": { home: "/images/kits/turska-home.webp" },
  "urugvaj": { home: "/images/kits/urugvaj-home.webp", away: "/images/kits/urugvaj-away.webp" },
  "uzbekistan": { home: "/images/kits/uzbekistan-home.webp", away: "/images/kits/uzbekistan-away.webp" },
};
