// AUTO-GENERATED — sve reprezentacije imaju home i away slike.
// Izuzeci: Irak i Iran (nemaju slike, koriste SVG placeholder).
// Slike se nalaze u /public/images/kits/<teamid>-home.png i <teamid>-away.png
export const KIT_IMAGES = {
  "alzir": { home: "/images/kits/alzir-home.png", away: "/images/kits/alzir-away.png" },
  "argentina": { home: "/images/kits/argentina-home.png", away: "/images/kits/argentina-away.png" },
  "australija": { home: "/images/kits/australija-home.png", away: "/images/kits/australija-away.png" },
  "austrija": { home: "/images/kits/austrija-home.png", away: "/images/kits/austrija-away.png" },
  "belgija": { home: "/images/kits/belgija-home.png", away: "/images/kits/belgija-away.png" },
  "bosna": { home: "/images/kits/bosna-home.png", away: "/images/kits/bosna-away.png" },
  "brazil": { home: "/images/kits/brazil-home.png", away: "/images/kits/brazil-away.png" },
  "ceska": { home: "/images/kits/ceska-home.png", away: "/images/kits/ceska-away.png" },
  "curacao": { home: "/images/kits/curacao-home.png", away: "/images/kits/curacao-away.png" },
  "drkongo": { home: "/images/kits/drkongo-home.png", away: "/images/kits/drkongo-away.png" },
  "egipat": { home: "/images/kits/egipat-home.png", away: "/images/kits/egipat-away.png" },
  "ekvador": { home: "/images/kits/ekvador-home.png", away: "/images/kits/ekvador-away.png" },
  "engleska": { home: "/images/kits/engleska-home.png", away: "/images/kits/engleska-away.png" },
  "france": { home: "/images/kits/france-home.png", away: "/images/kits/france-away.png" },
  "gana": { home: "/images/kits/gana-home.png", away: "/images/kits/gana-away.png" },
  "haiti": { home: "/images/kits/haiti-home.png", away: "/images/kits/haiti-away.png" },
  "holandija": { home: "/images/kits/holandija-home.png", away: "/images/kits/holandija-away.png" },
  "hrvatska": { home: "/images/kits/hrvatska-home.png", away: "/images/kits/hrvatska-away.png" },
  "japan": { home: "/images/kits/japan-home.png", away: "/images/kits/japan-away.png" },
  "jordan": { home: "/images/kits/jordan-home.png", away: "/images/kits/jordan-away.png" },
  "juznaafrika": { home: "/images/kits/juznaafrika-home.png", away: "/images/kits/juznaafrika-away.png" },
  "juznakoreja": { home: "/images/kits/juznakoreja-home.png", away: "/images/kits/juznakoreja-away.png" },
  "kanada": { home: "/images/kits/kanada-home.png", away: "/images/kits/kanada-away.png" },
  "kapeverde": { home: "/images/kits/kapeverde-home.png", away: "/images/kits/kapeverde-away.png" },
  "katar": { home: "/images/kits/katar-home.png", away: "/images/kits/katar-away.png" },
  "kolumbija": { home: "/images/kits/kolumbija-home.png", away: "/images/kits/kolumbija-away.png" },
  "maroko": { home: "/images/kits/maroko-home.png", away: "/images/kits/maroko-away.png" },
  "meksiko": { home: "/images/kits/meksiko-home.png", away: "/images/kits/meksiko-away.png" },
  "nemacka": { home: "/images/kits/nemacka-home.png", away: "/images/kits/nemacka-away.png" },
  "norveska": { home: "/images/kits/norveska-home.png", away: "/images/kits/norveska-away.png" },
  "novizeland": { home: "/images/kits/novizeland-home.png", away: "/images/kits/novizeland-away.png" },
  "obala": { home: "/images/kits/obala-home.png", away: "/images/kits/obala-away.png" },
  "panama": { home: "/images/kits/panama-home.png", away: "/images/kits/panama-away.png" },
  "paragvaj": { home: "/images/kits/paragvaj-home.png", away: "/images/kits/paragvaj-away.png" },
  "portugal": { home: "/images/kits/portugal-home.png", away: "/images/kits/portugal-away.png" },
  "sad": { home: "/images/kits/sad-home.png", away: "/images/kits/sad-away.png" },
  "saudijska": { home: "/images/kits/saudijska-home.png", away: "/images/kits/saudijska-away.png" },
  "senegal": { home: "/images/kits/senegal-home.png", away: "/images/kits/senegal-away.png" },
  "skotska": { home: "/images/kits/skotska-home.png", away: "/images/kits/skotska-away.png" },
  "spanija": { home: "/images/kits/spanija-home.png", away: "/images/kits/spanija-away.png" },
  "svajcarska": { home: "/images/kits/svajcarska-home.png", away: "/images/kits/svajcarska-away.png" },
  "svedska": { home: "/images/kits/svedska-home.png", away: "/images/kits/svedska-away.png" },
  "tunis": { home: "/images/kits/tunis-home.png", away: "/images/kits/tunis-away.png" },
  "turska": { home: "/images/kits/turska-home.png", away: "/images/kits/turska-away.png" },
  "urugvaj": { home: "/images/kits/urugvaj-home.png", away: "/images/kits/urugvaj-away.png" },
  "uzbekistan": { home: "/images/kits/uzbekistan-home.png", away: "/images/kits/uzbekistan-away.png" },
};
