// World Cup 2026 qualified national teams data
// Each team: name (Serbian), flag emoji, confederation, jersey colors for home/away, unique SEO description

export const WC_TEAMS = [
  {
    id: "argentina", name: "Argentina", flag: "🇦🇷", conf: "Južna Amerika",
    home: { primary: "#75AADB", secondary: "#ffffff" },
    away: { primary: "#1a1a2e", secondary: "#75AADB" },
    descHome: "Domaći dres aktuelnih svetskih prvaka. Legendarne nebo-plave i bele pruge koje su osvojile svet u Kataru. Nosi boje Mesijeve Argentine i budi deo istorije na Svetskom prvenstvu 2026.",
    descAway: "Gostujući dres Argentine u elegantnoj tamnoj varijanti. Moderan dizajn za prave navijače Albiceleste. Savršen spoj tradicije i savremenog stila.",
  },
  {
    id: "brazil", name: "Brazil", flag: "🇧🇷", conf: "Južna Amerika",
    home: { primary: "#FFDF00", secondary: "#009C3B" },
    away: { primary: "#002776", secondary: "#FFDF00" },
    descHome: "Ikonični žuti dres petostrukih svetskih šampiona. Canarinho boja koja simbolizuje najlepši fudbal na planeti. Obavezan komad za svakog ljubitelja samba fudbala.",
    descAway: "Plavi gostujući dres Brazila sa zlatnim detaljima. Elegancija i strast u jednom dresu. Pokaži ljubav prema Seleção u svakoj prilici.",
  },
  {
    id: "portugal", name: "Portugal", flag: "🇵🇹", conf: "Evropa",
    home: { primary: "#C8102E", secondary: "#006847" },
    away: { primary: "#ffffff", secondary: "#C8102E" },
    descHome: "Crveno-zeleni domaći dres portugalske reprezentacije. Boje Seleção das Quinas koje nose najveće zvezde svetskog fudbala. Vrhunski kvalitet za prave navijače.",
    descAway: "Beli gostujući dres Portugala sa suptilnim detaljima. Čist i moderan dizajn dostojan evropskog prvaka. Idealan za svakodnevno nošenje i utakmice.",
  },
  {
    id: "france", name: "Francuska", flag: "🇫🇷", conf: "Evropa",
    home: { primary: "#002654", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#002654" },
    descHome: "Tamno plavi dres Les Bleus, dvostrukih svetskih prvaka. Boje koje su osvojile svet 1998. i 2018. godine. Premium kvalitet za navijače francuske reprezentacije.",
    descAway: "Beli gostujući dres Francuske sa tricolore akcentima. Elegantan i prepoznatljiv dizajn. Nosi boje jedne od najjačih reprezentacija sveta.",
  },
  {
    id: "engleska", name: "Engleska", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", conf: "Evropa",
    home: { primary: "#ffffff", secondary: "#C8102E" },
    away: { primary: "#C8102E", secondary: "#ffffff" },
    descHome: "Beli domaći dres Tri lava sa crvenim akcentima. Tradicionalni izgled engleske reprezentacije spojen sa modernim krojem. Za prave navijače Three Lions.",
    descAway: "Crveni gostujući dres Engleske, podsećanje na slavnu 1966. godinu. Smeo i prepoznatljiv dizajn. Savršen za svakog ljubitelja engleskog fudbala.",
  },
  {
    id: "nemacka", name: "Nemačka", flag: "🇩🇪", conf: "Evropa",
    home: { primary: "#ffffff", secondary: "#000000" },
    away: { primary: "#000000", secondary: "#DD0000" },
    descHome: "Beli domaći dres četvorostrukih svetskih prvaka. Die Mannschaft tradicija u modernom izdanju. Vrhunski materijal za navijače nemačke mašine.",
    descAway: "Crni gostujući dres Nemačke sa upečatljivim detaljima. Moćan i moderan dizajn. Pokaži poštovanje prema jednoj od najuspešnijih reprezentacija.",
  },
  {
    id: "spanija", name: "Španija", flag: "🇪🇸", conf: "Evropa",
    home: { primary: "#C60B1E", secondary: "#FFC400" },
    away: { primary: "#1a1a2e", secondary: "#C60B1E" },
    descHome: "Crveni domaći dres La Roja, svetskih prvaka iz 2010. Boje koje predstavljaju tiki-taka filozofiju i tehnički savršen fudbal. Za prave navijače Furia Roja.",
    descAway: "Tamni gostujući dres Španije sa crvenim i zlatnim detaljima. Elegantan dizajn dostojan šampiona. Moderan komad za svaku priliku.",
  },
  {
    id: "hrvatska", name: "Hrvatska", flag: "🇭🇷", conf: "Evropa",
    home: { primary: "#FF0000", secondary: "#ffffff" },
    away: { primary: "#1a1a2e", secondary: "#FF0000" },
    descHome: "Prepoznatljivi kockasti dres hrvatske reprezentacije. Crveno-beli šahovnica koja je očarala svet. Vatreni dizajn za balkanske navijače i kolekcionare.",
    descAway: "Tamni gostujući dres Hrvatske sa kockastim detaljima. Moderna varijanta legendarnog dresa. Idealan za navijače Kockastih.",
  },
  {
    id: "srbija", name: "Srbija", flag: "🇷🇸", conf: "Evropa",
    home: { primary: "#C6363C", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#C6363C" },
    descHome: "Crveni domaći dres naših Orlova. Nosi boje Srbije sa ponosom na Svetskom prvenstvu 2026. Najtraženiji dres među domaćim navijačima — pravi izbor za svakog patriotu.",
    descAway: "Beli gostujući dres Srbije sa nacionalnim grbom. Elegantan i ponosit dizajn. Podrži naše Orlove gde god da igraju.",
  },
  {
    id: "holandija", name: "Holandija", flag: "🇳🇱", conf: "Evropa",
    home: { primary: "#FF6200", secondary: "#ffffff" },
    away: { primary: "#1a1a2e", secondary: "#FF6200" },
    descHome: "Narandžasti dres Oranje, prepoznatljiv širom sveta. Boja totalnog fudbala i holandske fudbalske škole. Vrhunski kvalitet za navijače Lale.",
    descAway: "Tamni gostujući dres Holandije sa narandžastim akcentima. Moderan i upečatljiv dizajn. Za sve ljubitelje holandskog fudbala.",
  },
  {
    id: "belgija", name: "Belgija", flag: "🇧🇪", conf: "Evropa",
    home: { primary: "#C8102E", secondary: "#FDDA24" },
    away: { primary: "#1a1a2e", secondary: "#C8102E" },
    descHome: "Crveni domaći dres Crvenih đavola. Zlatna generacija belgijskog fudbala u premium izdanju. Za navijače jedne od najtalentovanijih reprezentacija.",
    descAway: "Tamni gostujući dres Belgije sa zlatnim detaljima. Moderan dizajn dostojan Red Devils. Savršen za navijače i kolekcionare.",
  },
  {
    id: "meksiko", name: "Meksiko", flag: "🇲🇽", conf: "Severna Amerika",
    home: { primary: "#006847", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#006847" },
    descHome: "Zeleni domaći dres El Tri, domaćina Svetskog prvenstva 2026. Strastveni dizajn meksičke reprezentacije. Nosi boje jedne od najvatrenijih navijačkih baza sveta.",
    descAway: "Beli gostujući dres Meksika sa zelenim akcentima. Svež i moderan izgled. Podrži El Tri na domaćem Mundijalu.",
  },
  {
    id: "japan", name: "Japan", flag: "🇯🇵", conf: "Azija",
    home: { primary: "#0033A0", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#0033A0" },
    descHome: "Plavi domaći dres Samurai Blue. Spoj japanske preciznosti i modernog dizajna. Za navijače jedne od najbrže rastućih fudbalskih nacija sveta.",
    descAway: "Beli gostujući dres Japana sa elegantnim plavim detaljima. Minimalistički i sofisticiran dizajn. Savršen za prave ljubitelje azijskog fudbala.",
  },
  {
    id: "maroko", name: "Maroko", flag: "🇲🇦", conf: "Afrika",
    home: { primary: "#C1272D", secondary: "#006233" },
    away: { primary: "#ffffff", secondary: "#C1272D" },
    descHome: "Crveni dres marokanskih Atlaskih lavova, polufinalista 2022. Boje koje su ujedinile ceo arapski i afrički svet. Za navijače najveće senzacije prošlog Mundijala.",
    descAway: "Beli gostujući dres Maroka sa crvenim i zelenim detaljima. Elegantan dizajn dostojan polufinalista. Idealan za navijače Atlas lavova.",
  },
  {
    id: "sad", name: "SAD", flag: "🇺🇸", conf: "Severna Amerika",
    home: { primary: "#ffffff", secondary: "#002868" },
    away: { primary: "#002868", secondary: "#BF0A30" },
    descHome: "Beli domaći dres reprezentacije SAD, jednog od domaćina Mundijala 2026. Moderan dizajn za novu generaciju američkog fudbala. Za navijače USMNT.",
    descAway: "Tamno plavi gostujući dres SAD sa zvezdama i prugama. Patriotski i moderan dizajn. Podrži domaćine na najvećem fudbalskom spektaklu.",
  },
  {
    id: "kanada", name: "Kanada", flag: "🇨🇦", conf: "Severna Amerika",
    home: { primary: "#FF0000", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#FF0000" },
    descHome: "Crveni domaći dres Kanade, domaćina Svetskog prvenstva 2026. Boje javorovog lista u modernom izdanju. Za navijače reprezentacije u usponu.",
    descAway: "Beli gostujući dres Kanade sa crvenim javorovim listom. Čist i prepoznatljiv dizajn. Savršen za podršku domaćinima Mundijala.",
  },
  {
    id: "italija", name: "Italija", flag: "🇮🇹", conf: "Evropa",
    home: { primary: "#0066A6", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#0066A6" },
    descHome: "Azzurri plavi dres četvorostrukih svetskih prvaka. Boja koja predstavlja vrhunsku italijansku fudbalsku tradiciju. Za prave navijače Gli Azzurri.",
    descAway: "Beli gostujući dres Italije sa plavim akcentima. Elegantan i bezvremenski dizajn. Idealan za ljubitelje katenačo škole.",
  },
  {
    id: "kolumbija", name: "Kolumbija", flag: "🇨🇴", conf: "Južna Amerika",
    home: { primary: "#FCD116", secondary: "#003893" },
    away: { primary: "#003893", secondary: "#FCD116" },
    descHome: "Žuti domaći dres Los Cafeteros. Vatrene boje kolumbijskog fudbala i strastvenog navijanja. Za sve ljubitelje južnoameričke fudbalske magije.",
    descAway: "Plavi gostujući dres Kolumbije sa žutim i crvenim detaljima. Moderan i energičan dizajn. Savršen za navijače Cafeteros.",
  },
  {
    id: "urugvaj", name: "Urugvaj", flag: "🇺🇾", conf: "Južna Amerika",
    home: { primary: "#5CBFEB", secondary: "#ffffff" },
    away: { primary: "#1a1a2e", secondary: "#5CBFEB" },
    descHome: "Svetlo plavi dres La Celeste, prvih svetskih prvaka u istoriji. Boje ponosne fudbalske nacije sa najvećom tradicijom po glavi stanovnika. Za prave znalce fudbala.",
    descAway: "Tamni gostujući dres Urugvaja sa nebo-plavim detaljima. Moderan dizajn dostojan dvostrukih šampiona. Idealan za navijače Charrúas.",
  },
  {
    id: "ekvador", name: "Ekvador", flag: "🇪🇨", conf: "Južna Amerika",
    home: { primary: "#FFD100", secondary: "#0072CE" },
    away: { primary: "#0072CE", secondary: "#FFD100" },
    descHome: "Žuti domaći dres La Tri sa plavim i crvenim detaljima. Energične boje ekvadorske reprezentacije u usponu. Za navijače mlade i talentovane selekcije.",
    descAway: "Plavi gostujući dres Ekvadora sa živopisnim akcentima. Moderan i dinamičan dizajn. Savršen za ljubitelje južnoameričkog fudbala.",
  },
  {
    id: "paragvaj", name: "Paragvaj", flag: "🇵🇾", conf: "Južna Amerika",
    home: { primary: "#D52B1E", secondary: "#0038A8" },
    away: { primary: "#ffffff", secondary: "#D52B1E" },
    descHome: "Crveno-beli prugasti dres La Albirroja. Tradicionalni izgled paragvajske reprezentacije sa borbenim duhom. Za prave navijače Guaraníes.",
    descAway: "Beli gostujući dres Paragvaja sa crvenim i plavim detaljima. Čist i elegantan dizajn. Idealan za navijače paragvajskog fudbala.",
  },
  {
    id: "juznakoreja", name: "Južna Koreja", flag: "🇰🇷", conf: "Azija",
    home: { primary: "#C8102E", secondary: "#003478" },
    away: { primary: "#ffffff", secondary: "#C8102E" },
    descHome: "Crveni dres Taegeuk ratnika. Strastvene boje korejske reprezentacije i Red Devils navijača. Za ljubitelje brzog i tehničkog azijskog fudbala.",
    descAway: "Beli gostujući dres Južne Koreje sa crvenim i plavim akcentima. Moderan i dinamičan dizajn. Savršen za navijače Taeguk Warriors.",
  },
  {
    id: "australija", name: "Australija", flag: "🇦🇺", conf: "Azija",
    home: { primary: "#FFCD00", secondary: "#00843D" },
    away: { primary: "#00843D", secondary: "#FFCD00" },
    descHome: "Žuti dres Socceroosa sa zelenim detaljima. Prepoznatljive boje australijske reprezentacije i borbenog duha. Za navijače Down Under selekcije.",
    descAway: "Zeleni gostujući dres Australije sa žutim akcentima. Moderan i upečatljiv dizajn. Idealan za ljubitelje Socceroos.",
  },
  {
    id: "iran", name: "Iran", flag: "🇮🇷", conf: "Azija",
    home: { primary: "#ffffff", secondary: "#239F40" },
    away: { primary: "#C8102E", secondary: "#ffffff" },
    descHome: "Beli domaći dres Team Melli sa zelenim i crvenim detaljima. Ponosne boje iranske reprezentacije, najjače azijske nacije. Za prave navijače persijskog fudbala.",
    descAway: "Crveni gostujući dres Irana sa nacionalnim akcentima. Smeo i moderan dizajn. Savršen za navijače Team Melli.",
  },
  {
    id: "saudijska", name: "Saudijska Arabija", flag: "🇸🇦", conf: "Azija",
    home: { primary: "#ffffff", secondary: "#006C35" },
    away: { primary: "#006C35", secondary: "#ffffff" },
    descHome: "Beli dres Sokolova sa zelenim detaljima. Boje saudijske reprezentacije koja je šokirala Argentinu u Kataru. Za navijače najambicioznije azijske nacije.",
    descAway: "Zeleni gostujući dres Saudijske Arabije. Elegantan dizajn sa nacionalnim ponosom. Idealan za ljubitelje arapskog fudbala.",
  },
  {
    id: "japan2", name: "Katar", flag: "🇶🇦", conf: "Azija",
    home: { primary: "#8A1538", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#8A1538" },
    descHome: "Bordo dres katarske reprezentacije, azijskih šampiona. Prepoznatljive boje domaćina prošlog Mundijala. Za navijače ambiciozne arapske selekcije.",
    descAway: "Beli gostujući dres Katara sa bordo detaljima. Moderan i sofisticiran dizajn. Savršen za ljubitelje azijskog fudbala.",
  },
  {
    id: "maroko2", name: "Senegal", flag: "🇸🇳", conf: "Afrika",
    home: { primary: "#ffffff", secondary: "#00853F" },
    away: { primary: "#00853F", secondary: "#FDEF42" },
    descHome: "Beli dres Terangskih lavova, afričkih šampiona. Ponosne boje senegalske reprezentacije sa zvezdama poput Manea. Za navijače najjače afričke nacije.",
    descAway: "Zeleni gostujući dres Senegala sa žutim i crvenim detaljima. Energičan i moderan dizajn. Idealan za ljubitelje afričkog fudbala.",
  },
  {
    id: "gana", name: "Gana", flag: "🇬🇭", conf: "Afrika",
    home: { primary: "#ffffff", secondary: "#CE1126" },
    away: { primary: "#000000", secondary: "#FCD116" },
    descHome: "Beli dres Black Stars sa nacionalnim bojama. Ponosni izgled ganske reprezentacije sa bogatom afričkom tradicijom. Za navijače Crnih zvezda.",
    descAway: "Crni gostujući dres Gane sa zlatnim detaljima. Moćan i upečatljiv dizajn. Savršen za ljubitelje afričkog fudbala.",
  },
  {
    id: "obala", name: "Obala Slonovače", flag: "🇨🇮", conf: "Afrika",
    home: { primary: "#FF8200", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#FF8200" },
    descHome: "Narandžasti dres Slonova, afričkih šampiona 2023. Vatrene boje reprezentacije Obale Slonovače. Za navijače jedne od najjačih afričkih selekcija.",
    descAway: "Beli gostujući dres Obale Slonovače sa narandžastim i zelenim detaljima. Moderan dizajn dostojan šampiona Afrike.",
  },
  {
    id: "egipat", name: "Egipat", flag: "🇪🇬", conf: "Afrika",
    home: { primary: "#C8102E", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#000000" },
    descHome: "Crveni dres faraona predvođenih Mohamedom Salahom. Ponosne boje najuspešnije afričke reprezentacije u istoriji. Za navijače The Pharaohs.",
    descAway: "Beli gostujući dres Egipta sa crnim i crvenim detaljima. Elegantan i moderan dizajn. Savršen za ljubitelje egipatskog fudbala.",
  },
  {
    id: "alzir", name: "Alžir", flag: "🇩🇿", conf: "Afrika",
    home: { primary: "#ffffff", secondary: "#006233" },
    away: { primary: "#006233", secondary: "#ffffff" },
    descHome: "Beli dres Pustinjskih lisica sa zelenim detaljima. Ponosne boje alžirske reprezentacije i strastvene navijačke baze. Za ljubitelje severnoafričkog fudbala.",
    descAway: "Zeleni gostujući dres Alžira sa belim akcentima. Moderan i energičan dizajn. Idealan za navijače Les Fennecs.",
  },
  {
    id: "juznaafrika", name: "Južna Afrika", flag: "🇿🇦", conf: "Afrika",
    home: { primary: "#FFB81C", secondary: "#007749" },
    away: { primary: "#007749", secondary: "#FFB81C" },
    descHome: "Žuti dres Bafana Bafana sa zelenim detaljima. Vesele boje južnoafričke reprezentacije i nezaboravne 2010. godine. Za navijače domaćina prvog afričkog Mundijala.",
    descAway: "Zeleni gostujući dres Južne Afrike sa žutim akcentima. Moderan i prepoznatljiv dizajn. Savršen za ljubitelje afričkog fudbala.",
  },
  {
    id: "tunis", name: "Tunis", flag: "🇹🇳", conf: "Afrika",
    home: { primary: "#E70013", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#E70013" },
    descHome: "Crveni dres Orlova Kartagine. Ponosne boje tuniske reprezentacije sa bogatom istorijom. Za navijače jedne od najstabilnijih afričkih selekcija.",
    descAway: "Beli gostujući dres Tunisa sa crvenim detaljima. Čist i elegantan dizajn. Idealan za ljubitelje severnoafričkog fudbala.",
  },
  {
    id: "norveska", name: "Norveška", flag: "🇳🇴", conf: "Evropa",
    home: { primary: "#C8102E", secondary: "#00205B" },
    away: { primary: "#ffffff", secondary: "#C8102E" },
    descHome: "Crveni dres norveške reprezentacije predvođene Erlingom Halandom. Boje skandinavske sile u usponu. Za navijače jedne od najuzbudljivijih selekcija.",
    descAway: "Beli gostujući dres Norveške sa crvenim i plavim detaljima. Moderan i minimalistički dizajn. Savršen za ljubitelje nordijskog fudbala.",
  },
  {
    id: "svajcarska", name: "Švajcarska", flag: "🇨🇭", conf: "Evropa",
    home: { primary: "#D52B1E", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#D52B1E" },
    descHome: "Crveni dres švajcarske reprezentacije sa belim krstom. Precizan i pouzdan kao i švajcarski fudbal. Za navijače Nati selekcije.",
    descAway: "Beli gostujući dres Švajcarske sa crvenim detaljima. Elegantan i čist dizajn. Idealan za ljubitelje evropskog fudbala.",
  },
  {
    id: "skotska", name: "Škotska", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", conf: "Evropa",
    home: { primary: "#0065BD", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#0065BD" },
    descHome: "Tamno plavi dres Tartan Army. Ponosne boje škotske reprezentacije sa strastvenom navijačkom bazom. Za ljubitelje britanskog fudbala.",
    descAway: "Beli gostujući dres Škotske sa plavim detaljima. Moderan i prepoznatljiv dizajn. Savršen za navijače Tartan Army.",
  },
  {
    id: "austrija", name: "Austrija", flag: "🇦🇹", conf: "Evropa",
    home: { primary: "#ED2939", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#ED2939" },
    descHome: "Crveni dres austrijske reprezentacije. Boje Das Team selekcije sa rastućim ambicijama. Za navijače srednjoevropskog fudbala.",
    descAway: "Beli gostujući dres Austrije sa crvenim detaljima. Čist i moderan dizajn. Idealan za ljubitelje evropskog fudbala.",
  },
  {
    id: "ceska", name: "Češka", flag: "🇨🇿", conf: "Evropa",
    home: { primary: "#D7141A", secondary: "#ffffff" },
    away: { primary: "#11457E", secondary: "#ffffff" },
    descHome: "Crveni dres češke reprezentacije sa belim i plavim detaljima. Ponosne boje srednjoevropske fudbalske tradicije. Za navijače Národní tým.",
    descAway: "Plavi gostujući dres Češke sa belim akcentima. Moderan i elegantan dizajn. Savršen za ljubitelje evropskog fudbala.",
  },
  {
    id: "novizeland", name: "Novi Zeland", flag: "🇳🇿", conf: "Okeanija",
    home: { primary: "#ffffff", secondary: "#000000" },
    away: { primary: "#000000", secondary: "#ffffff" },
    descHome: "Beli dres All Whites, predstavnika Okeanije. Ponosne boje novozelandske reprezentacije sa borbenim duhom. Za ljubitelje fudbala sa kraja sveta.",
    descAway: "Crni gostujući dres Novog Zelanda. Moćan i upečatljiv dizajn inspirisan All Blacks tradicijom. Savršen za prave navijače.",
  },
  {
    id: "uzbekistan", name: "Uzbekistan", flag: "🇺🇿", conf: "Azija",
    home: { primary: "#1EB53A", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#1EB53A" },
    descHome: "Zeleni dres uzbekistanske reprezentacije, debitanata na Mundijalu. Ponosne boje azijske selekcije u istorijskom trenutku. Za navijače White Wolves.",
    descAway: "Beli gostujući dres Uzbekistana sa zelenim i plavim detaljima. Moderan dizajn za istorijski debi. Idealan za ljubitelje azijskog fudbala.",
  },
  {
    id: "jordan", name: "Jordan", flag: "🇯🇴", conf: "Azija",
    home: { primary: "#ffffff", secondary: "#CE1126" },
    away: { primary: "#000000", secondary: "#CE1126" },
    descHome: "Beli dres jordanske reprezentacije, debitanata na Svetskom prvenstvu. Ponosne boje arapske selekcije u istorijskom trenutku. Za navijače Al-Nashama.",
    descAway: "Crni gostujući dres Jordana sa crvenim detaljima. Smeo i moderan dizajn za istorijski debi. Savršen za ljubitelje arapskog fudbala.",
  },
  {
    id: "kapeverde", name: "Zelenortska Ostrva", flag: "🇨🇻", conf: "Afrika",
    home: { primary: "#003893", secondary: "#ffffff" },
    away: { primary: "#ffffff", secondary: "#003893" },
    descHome: "Plavi dres Ajkula, debitanata na Mundijalu. Ponosne boje najmanje nacije na Svetskom prvenstvu. Za navijače koji vole fudbalske bajke.",
    descAway: "Beli gostujući dres Zelenortskih Ostrva sa plavim detaljima. Moderan dizajn za istorijski debi. Idealan za ljubitelje afričkog fudbala.",
  },
];

export const SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
